language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - DISTRO="ubuntu"
  - PINS="faraday-async:. faraday-lwt:. faraday-lwt-unix:. faraday:."
  - PACKAGE="faraday"
  - TESTS=true
  - POST_INSTALL_HOOK="opam install --with-test faraday-async faraday-lwt faraday-lwt-unix'
  matrix:
  - OCAML_VERSION="4.07"
  - OCAML_VERSION="4.06"
  - OCAML_VERSION="4.05"
